### ISSUE TITLE
Godot 4 port?

### ISSUE THREAD

**Issue by me2beats** [bifractal/godot-water-transition-shader#1]
Hello thanks for the beautiful shader.
Can it be ported to Godot 4?

**Comment by bifractal** [comment]
Hi @me2beats,

I've pushed a quick port for Godot 4. Checkout the **godot4** branch: https://github.com/bifractal/godot-water-transition-shader/tree/godot4.

**Comment by me2beats** [comment]
Thanks a lot!
I have some issues tho
I will create new issues rather than write them here
I guess I can close this one
