### ISSUE TITLE
Godot 4: water plane produces black areas when the camera looks down

### ISSUE THREAD

**Issue by me2beats** [bifractal/godot-water-transition-shader#2]
[test transition water fixed visuals.zip](https://github.com/bifractal/godot-water-transition-shader/files/11642870/test.transition.water.fixed.visuals.zip)

I can see these black areas when the camera looks down at some angle

![image](https://github.com/bifractal/godot-water-transition-shader/assets/16458555/ddf857f9-01ff-4339-b7cd-23a755a939d2)

even in the editor:

![image](https://github.com/bifractal/godot-water-transition-shader/assets/16458555/1364a02c-4a77-484e-a0d9-bd33220bfc84)

When I remove the water plane, the issue is gone

Can someone check the project?
Maybe I miss something
or maybe this is system specific issue (I test it now on NVIDIA GeForce GT 1030, Windows)

**Comment by bifractal** [comment]
Hi @me2beats,

this is fixed for the ocean shader and was caused by a non-clamped distance value.

Thanks for reporting, had the same issue, but only inside the editor.
